### ISSUE TITLE
Undefined player in key-press simulation

### ISSUE THREAD

**Issue by SnoopJ** [OmarShehata/Airena#1]
When using on the web, execution will fail because `pl` is set to undefined at [init.js:L250](https://github.com/OmarShehata/Airena/blob/master/src/init.js#L250).  This could be a problem with unreliable sockets (stepping into the socket handler for `initial-users` shows that `player.id` is out of step with `msg.id` pretty much immediately), but at the very least there should be a test here to avoid a hard failure.

**Comment by OmarShehata** [comment]
That's interesting! Does that always happen for you? I have noticed that error in the web console. Restarting the server seems to fix this (and other issues). I suppose ensuring that the client has initialized its list of players before accepting any other messages would be an easy fix for this?

**Comment by SnoopJ** [comment]
I think I've had it behave properly a few times on the hosted version, but more often it exhibits this behavior.  

Yea, that'd do the trick.  You probably want to write a `getPlayer(id)` function, so that you don't need a test everytime you want to touch `playerArray`.
